using System.Diagnostics;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Net.Sockets;
using System.Text.Json;
using RemoteAssist.Inventory;
using RemoteAssist.Inventory.Server;

if (args.Contains("--container-smoke")) { await ContainerSmoke.Run(); return; }

var root = Path.Combine(Path.GetTempPath(), "remoteassist-inventory-tests-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
var store = new InventoryStore(Path.Combine(root, "data"));
store.BootstrapOwner("owner", "test-password-12345");
var ownerLogin = store.Login(new LoginRequest { Username = "owner", Password = "test-password-12345" });
var owner = ownerLogin.User;
var checks = 0;
void Check(bool condition, string name) { if (!condition) throw new Exception("FAILED: " + name); checks++; Console.WriteLine("PASS " + name); }
void Error(int status, Action action, string name) { try { action(); throw new Exception("Expected failure: " + name); } catch (StoreException ex) { Check(ex.Status == status, name); } }
T Clone<T>(T item) => JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(item, InventoryStore.Json), InventoryStore.Json)!;
AssetDto Asset(string id) => store.Snapshot().Assets.Single(a => a.Id == id);
CartridgeDto Cartridge(string id) => store.Snapshot().Cartridges.Single(a => a.Id == id);
Check(store.Authenticate(ownerLogin.Token).Role == "owner", "hashed opaque bearer token accepted");
Error(401, () => store.Login(new LoginRequest { Username = "owner", Password = "bad-password" }), "wrong password rejected");
var editorUser = new UserDto { Username = "editor", DisplayName = "Лаборант", Role = "editor" };
store.SaveUser(new SaveUserCommand { Value = editorUser, Password = "test-editor-12345" }, owner);
var editorLogin = store.Login(new LoginRequest { Username = "editor", Password = "test-editor-12345" }); var editor = editorLogin.User;
Error(403, () => store.Users(editor), "editor cannot administer users");
Error(400, () => store.SaveUser(new SaveUserCommand { Value = new UserDto { Id = owner.Id, Version = owner.Version, Username = owner.Username, Role = "editor" } }, owner), "last owner cannot be removed");
var r1 = new RoomDto { Number = "201", Floor = 2 }; var r2 = new RoomDto { Number = "202", Floor = 2 };
store.SeedRooms(new SeedRoomsCommand { Rooms = [r1, r2] }, owner);
store.SeedRooms(new SeedRoomsCommand { Rooms = [r1, r2] }, editor);
Check(store.Snapshot().Rooms.Count == 2, "map seeds idempotent by exact room identity");
store.SeedRooms(new SeedRoomsCommand { Rooms = [new RoomDto { Number = " 201 ", Building = "д", Floor = 2 }] }, editor);
Check(store.Snapshot().Rooms.Count == 2, "map seed and duplicate-room validation share whitespace/case semantics");
var pc = new AssetDto { RoomId = r1.Id, Model = "ПК 1", InventoryNumber = "000123", Seat = "12" };
var createPc = new SaveCommand<AssetDto> { Value = pc }; store.SaveAsset(createPc, owner);
Check(store.SaveAsset(createPc, owner).AlreadyApplied && store.Snapshot().Assets.Count == 1, "retry returns persisted command result without duplicate");
var changedCommand = new SaveCommand<AssetDto> { CommandId = createPc.CommandId, Value = new AssetDto { Model = "Другой ПК" } };
Error(409, () => store.SaveAsset(changedCommand, owner), "idempotency key cannot be reused with different payload");
var aView = Asset(pc.Id); var bView = Asset(pc.Id); aView.RoomId = r2.Id; aView.X = .2; aView.Y = .3;
store.SaveAsset(new SaveCommand<AssetDto> { Value = aView }, owner);
bView.Notes = "stale edit"; Error(409, () => store.SaveAsset(new SaveCommand<AssetDto> { Value = bView }, editor), "two-client stale edit cannot overwrite room transfer");
Check(Asset(pc.Id).RoomId == r2.Id && Asset(pc.Id).X is null, "transfer starts unplaced in exact destination 202");
var placed = Asset(pc.Id); placed.X = .25; placed.Y = .75; store.SaveAsset(new SaveCommand<AssetDto> { Value = placed }, owner);
Check(Asset(pc.Id).X == .25, "normalized placement persisted");
var duplicateInventory = new AssetDto { InventoryNumber = pc.InventoryNumber, Type = "Монитор", RoomId = r2.Id };
store.SaveAsset(new SaveCommand<AssetDto> { Value = duplicateInventory }, owner);
Check(store.Snapshot().Assets.Count == 2, "shared inventory numbers do not merge kit components");
var printer = new AssetDto { Type = "МФУ", RoomId = r2.Id, CompatibleCartridgeModels = ["CF259A"] };
store.SaveAsset(new SaveCommand<AssetDto> { Value = printer }, owner);
var c1 = new CartridgeDto { Number = "К-0001", Model = "CF259A" }; var c2 = new CartridgeDto { Number = "К-0002", Model = "CF259A" };
store.SaveCartridge(new SaveCommand<CartridgeDto> { Value = c1 }, owner); store.SaveCartridge(new SaveCommand<CartridgeDto> { Value = c2 }, owner);
Error(400, () => store.SaveCartridge(new SaveCommand<CartridgeDto> { Value = new CartridgeDto { Number = "к-0001", Model = "CF259A" } }, owner), "physical cartridge numbers are unique");
store.ReplaceCartridge(new ReplaceCartridgeCommand { PrinterId = printer.Id, PrinterVersion = Asset(printer.Id).Version, NewCartridgeId = c1.Id, NewCartridgeVersion = Cartridge(c1.Id).Version }, owner);
var printerTypeChange = Asset(printer.Id); printerTypeChange.Type = "Компьютер";
Error(400, () => store.SaveAsset(new SaveCommand<AssetDto> { Value = printerTypeChange }, owner), "installed cartridges prevent type changes that would trap attachments");
var failedReplace = new ReplaceCartridgeCommand { PrinterId = printer.Id, PrinterVersion = Asset(printer.Id).Version, OldCartridgeId = c1.Id, OldCartridgeVersion = Cartridge(c1.Id).Version, NewCartridgeId = c2.Id, NewCartridgeVersion = 999 };
Error(409, () => store.ReplaceCartridge(failedReplace, editor), "stale replacement rejected atomically");
Check(Cartridge(c1.Id).PrinterId == printer.Id && Cartridge(c2.Id).PrinterId is null, "failed replacement preserves both cartridges");
failedReplace.CommandId = Guid.NewGuid().ToString("N"); failedReplace.NewCartridgeVersion = Cartridge(c2.Id).Version; store.ReplaceCartridge(failedReplace, editor);
Check(Cartridge(c1.Id).Status == "На заправке" && Cartridge(c2.Id).PrinterId == printer.Id, "replacement removes and installs atomically");
var secondPrinter = new AssetDto { Type = "Принтер", RoomId = r1.Id }; store.SaveAsset(new SaveCommand<AssetDto> { Value = secondPrinter }, owner);
Error(400, () => store.ReplaceCartridge(new ReplaceCartridgeCommand { PrinterId = secondPrinter.Id, PrinterVersion = Asset(secondPrinter.Id).Version, NewCartridgeId = c2.Id, NewCartridgeVersion = Cartridge(c2.Id).Version }, owner), "one cartridge cannot be installed in two printers");
var png = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=");
var photoCommand = Guid.NewGuid().ToString("N"); store.UploadPhoto(photoCommand, "asset", pc.Id, "Рабочее место", png, owner);
Check(store.UploadPhoto(photoCommand, "asset", pc.Id, "Рабочее место", png, owner).AlreadyApplied && store.Snapshot().Photos.Count == 1, "photo upload retry creates exactly one immutable file");
Error(400, () => store.UploadPhoto(Guid.NewGuid().ToString("N"), "asset", pc.Id, "", new byte[] { 0, 1, 2 }, owner), "invalid image signature rejected");
var audit = new AuditDto { Name = "Сверка второго этажа", Scope = "floor", Floor = 2 };
var unnamedEditor = Clone(editor); unnamedEditor.DisplayName = "";
store.CreateAudit(new SaveCommand<AuditDto> { Value = audit }, unnamedEditor);
var snapshotAudit = store.Snapshot().Audits.Single(); var pcItem = snapshotAudit.Items.Single(x => x.AssetId == pc.Id);
Check(snapshotAudit.CreatedBy == editor.Username, "audit creator falls back to username when display name is blank");
Check(pcItem.ExpectedRoomId == r2.Id && pcItem.ExpectedRoomNumber.StartsWith("202") && pcItem.AssetSnapshot.InventoryNumber == "000123", "audit captures independent expected-room and asset snapshot");
Check(pcItem.ExpectedRoomSnapshot?.Floor == 2 && pcItem.ExpectedRoomSnapshot.Building == "Д", "audit snapshots room floor and building instead of guessing from the room number");
pcItem.Result = "Обнаружено в другом кабинете"; pcItem.ActualRoomId = r1.Id;
store.SaveAuditItem(new AuditItemCommand { AuditId = audit.Id, AuditVersion = snapshotAudit.Version, Value = pcItem }, unnamedEditor);
Check(Asset(pc.Id).RoomId == r2.Id, "audit finding never silently moves live equipment");
snapshotAudit = store.Snapshot().Audits.Single(); var checkedPc = snapshotAudit.Items.Single(x => x.AssetId == pc.Id);
Check(checkedPc.CheckedBy == editor.Username, "immutable audit inspector falls back to username when display name is blank");
store.UploadPhoto(Guid.NewGuid().ToString("N"), "auditItem", checkedPc.Id, "Обнаружено", png, editor);
var discovered = new AssetDto { Type = "Проектор", Model = "Ранее неучтённый", RoomId = r1.Id }; store.SaveAsset(new SaveCommand<AssetDto> { Value = discovered }, owner);
store.AddAuditAsset(new AuditAddAssetCommand { AuditId = audit.Id, Version = snapshotAudit.Version, AssetId = discovered.Id }, owner);
snapshotAudit = store.Snapshot().Audits.Single(); var discoveredItem = snapshotAudit.Items.Single(x => x.AssetId == discovered.Id);
Check(discoveredItem.AddedAfterStart && discoveredItem.ExpectedRoomId is null && discoveredItem.ActualRoomId == r1.Id, "discovered equipment is not retroactively added to expected starting inventory");
discoveredItem.Result = "Найдено"; store.SaveAuditItem(new AuditItemCommand { AuditId = audit.Id, AuditVersion = snapshotAudit.Version, Value = discoveredItem }, owner);
snapshotAudit = store.Snapshot().Audits.Single();
Check(snapshotAudit.Items.Single(x => x.AssetId == discovered.Id).ActualRoomId == r1.Id, "found unregistered equipment keeps its actual room separately");
store.CompleteAudit(new AuditCompleteCommand { AuditId = audit.Id, Version = snapshotAudit.Version }, owner);
var frozen = store.Snapshot().Audits.Single(); var frozenJson = JsonSerializer.Serialize(frozen, InventoryStore.Json);
Error(400, () => store.SaveAuditItem(new AuditItemCommand { AuditId = audit.Id, AuditVersion = frozen.Version, Value = checkedPc }, owner), "completed audit cannot be edited");
Error(400, () => store.UploadPhoto(Guid.NewGuid().ToString("N"), "auditItem", checkedPc.Id, "", png, owner), "completed audit photographs cannot be changed");
var renamedRoom = store.Snapshot().Rooms.Single(x => x.Id == r2.Id); renamedRoom.Floor = 4; renamedRoom.Number = "Серверная";
store.SaveRoom(new SaveCommand<RoomDto> { Value = renamedRoom }, owner);
var modified = Asset(pc.Id); modified.Model = "Заменённый компьютер"; store.SaveAsset(new SaveCommand<AssetDto> { Value = modified }, owner);
Check(JsonSerializer.Serialize(store.Snapshot().Audits.Single(), InventoryStore.Json) == frozenJson, "later room floor/name and asset changes cannot alter completed audit export");
var fileHash = new string('A', 64); var import = new ImportCommand { FileHash = fileHash, Assets = [new AssetDto { Type = "Монитор", Source = new ImportSourceDto { FileHash = fileHash, RowNumber = 1, RawCells = new() { ["J"] = "007", ["K"] = "999" } } }] };
store.Import(import, owner); var importedCount = store.Snapshot().Assets.Count;
store.Import(new ImportCommand { FileHash = fileHash, Assets = import.Assets }, editor);
Check(store.Snapshot().Assets.Count == importedCount && store.Snapshot().ImportedFileHashes.Count == 1, "same workbook hash is never imported twice across different command IDs");
var backups = Path.Combine(root, "backups"); var backup = store.CreateBackup(backups); InventoryStore.VerifyBackup(backup);
var backupHeader = File.ReadAllBytes(Path.Combine(backup, "inventory.db"));
Check(backupHeader[18] == 1 && backupHeader[19] == 1 && !File.Exists(Path.Combine(backup, "inventory.db-wal")) && !File.Exists(Path.Combine(backup, "inventory.db-shm")), "backup is standalone rollback-format SQLite for verification on read-only mounts");
var restoredDir = Path.Combine(root, "restored"); InventoryStore.RestoreBackup(backup, restoredDir); var restored = new InventoryStore(restoredDir);
Check(restored.Snapshot().Assets.Count == store.Snapshot().Assets.Count && restored.Snapshot().Photos.Count == 2 && File.Exists(restored.Photo(store.Snapshot().Photos[0].Id).Path), "consistent database+photo backup restores with verified hashes");
Check(restored.Snapshot().InstanceId == store.Snapshot().InstanceId, "normal restoration retains database identity and local computer links");
Error(401, () => restored.Authenticate(ownerLogin.Token), "restoration invalidates old sessions");
Check(restored.Login(new LoginRequest { Username = "owner", Password = "test-password-12345" }).User.Role == "owner", "restored password hashes allow fresh login");
try { InventoryStore.RestoreBackup(backup, restoredDir); throw new Exception("Expected nonempty restore refusal"); } catch (IOException) { Check(true, "restore never overwrites an existing dataset"); }
string lastBackup = "";
for (var i = 0; i < 15; i++) lastBackup = store.CreateBackup(backups);
Check(Directory.GetDirectories(backups, "inventory-*").Length == 14 && Directory.Exists(lastBackup) && !Directory.Exists(backup), "backup retention keeps newest 14 verified copies including same-second backups");

var corridor = new RoomDto { Number = "Коридор 2", Floor = 2, Kind = "corridor" };
store.SaveRoom(new SaveCommand<RoomDto> { Value = corridor }, owner);
var telephone = new AssetDto { Type = "Телефон", PhoneNumber = "+7 (3852) 00-00-00 доб. 012", RoomId = corridor.Id };
store.SaveAsset(new SaveCommand<AssetDto> { Value = telephone }, owner);
var corridorPhone = Asset(telephone.Id); corridorPhone.X = .25; corridorPhone.Y = .5;
store.SaveAsset(new SaveCommand<AssetDto> { Value = corridorPhone }, owner);
Check(Asset(telephone.Id).PhoneNumber == telephone.PhoneNumber && Asset(telephone.Id).X == .25 && store.Snapshot().Rooms.Single(x => x.Id == corridor.Id).Kind == "corridor", "phone number and corridor placement survive save/reload");
var component = Asset(duplicateInventory.Id); component.ParentAssetId = pc.Id;
store.SaveAsset(new SaveCommand<AssetDto> { Value = component }, owner);
Check(Asset(component.Id).ParentAssetId == pc.Id, "monitor can link to a computer independently of inventory numbers");
var cycle = Asset(pc.Id); cycle.ParentAssetId = component.Id;
Error(400, () => store.SaveAsset(new SaveCommand<AssetDto> { Value = cycle }, owner), "device relationship cycles rejected atomically");
var self = Asset(pc.Id); self.ParentAssetId = self.Id;
Error(400, () => store.SaveAsset(new SaveCommand<AssetDto> { Value = self }, owner), "device cannot link to itself");
var missing = Asset(pc.Id); missing.ParentAssetId = Guid.NewGuid().ToString("N");
Error(404, () => store.SaveAsset(new SaveCommand<AssetDto> { Value = missing }, owner), "device relationship must reference an existing object");
component = Asset(component.Id); component.ParentAssetId = null; store.SaveAsset(new SaveCommand<AssetDto> { Value = component }, owner);
Check(Asset(component.Id).ParentAssetId is null && store.Snapshot().History.Any(x => x.EntityId == component.Id && x.BeforeJson.Contains(pc.Id)), "unlink preserves the relationship change in history");

// Exercise real HTTP transport, authentication and two clients independently of the in-process store tests.
var serverAssembly = typeof(InventoryStore).Assembly.Location;
var secretFile = Path.Combine(root, "owner.secret"); File.WriteAllText(secretFile, "http-test-password-12345");
var listener = new TcpListener(IPAddress.Loopback, 0); listener.Start(); var port = ((IPEndPoint)listener.LocalEndpoint).Port; listener.Stop();
var start = new ProcessStartInfo("dotnet") { UseShellExecute = false, RedirectStandardOutput = true, RedirectStandardError = true, CreateNoWindow = true };
start.ArgumentList.Add(serverAssembly); start.Environment["ASPNETCORE_URLS"] = $"http://127.0.0.1:{port}"; start.Environment["INVENTORY_ALLOW_HTTP"] = "true"; start.Environment["INVENTORY_DATA_DIR"] = Path.Combine(root, "http-data"); start.Environment["INVENTORY_OWNER_USERNAME"] = "http-owner"; start.Environment["INVENTORY_OWNER_PASSWORD_FILE"] = secretFile;
using var process = Process.Start(start)!; var logs = process.StandardOutput.ReadToEndAsync(); var errors = process.StandardError.ReadToEndAsync();
try
{
    using var clientA = new HttpClient { BaseAddress = new Uri($"http://127.0.0.1:{port}") }; using var clientB = new HttpClient { BaseAddress = clientA.BaseAddress };
    var ready = false;
    for (var i = 0; i < 100 && !ready; i++) { if (process.HasExited) throw new Exception(await logs + await errors); try { ready = (await clientA.GetAsync("/api/health")).IsSuccessStatusCode; } catch (HttpRequestException) { await Task.Delay(100); } }
    Check(ready, "ASP.NET service starts with secret-file owner bootstrap");
    Check((await clientA.GetAsync("/api/snapshot")).StatusCode == HttpStatusCode.Unauthorized, "HTTP snapshot requires authentication");
    var loginA = await (await clientA.PostAsJsonAsync("/api/login", new LoginRequest { Username = "http-owner", Password = "http-test-password-12345" })).Content.ReadFromJsonAsync<LoginResponse>();
    var loginB = await (await clientB.PostAsJsonAsync("/api/login", new LoginRequest { Username = "http-owner", Password = "http-test-password-12345" })).Content.ReadFromJsonAsync<LoginResponse>();
    clientA.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", loginA!.Token); clientB.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", loginB!.Token);
    var httpRoom = new RoomDto { Number = "401", Floor = 4 }; (await clientA.PostAsJsonAsync("/api/rooms", new SaveCommand<RoomDto> { Value = httpRoom })).EnsureSuccessStatusCode();
    var roomA = (await clientA.GetFromJsonAsync<InventorySnapshot>("/api/snapshot"))!.Rooms.Single(); var roomB = Clone(roomA); roomA.Name = "Лаборатория";
    (await clientA.PostAsJsonAsync("/api/rooms", new SaveCommand<RoomDto> { Value = roomA })).EnsureSuccessStatusCode(); roomB.Name = "Устаревшая правка";
    var conflict = await clientB.PostAsJsonAsync("/api/rooms", new SaveCommand<RoomDto> { Value = roomB });
    Check(conflict.StatusCode == HttpStatusCode.Conflict && (await conflict.Content.ReadFromJsonAsync<ApiError>())!.Current is not null, "HTTP conflict 409 returns current data to preserve client draft");
    using var photoForm = new MultipartFormDataContent(); photoForm.Add(new StringContent(Guid.NewGuid().ToString("N")), "commandId"); photoForm.Add(new StringContent("room"), "ownerType"); photoForm.Add(new StringContent(httpRoom.Id), "ownerId"); photoForm.Add(new StringContent("Фото кабинета"), "caption"); photoForm.Add(new ByteArrayContent(png), "file", "room.png");
    (await clientA.PostAsync("/api/photos/upload", photoForm)).EnsureSuccessStatusCode();
    var photo = (await clientA.GetFromJsonAsync<InventorySnapshot>("/api/snapshot"))!.Photos.Single(); var photoResponse = await clientB.GetAsync($"/api/photos/{photo.Id}/content");
    Check(photoResponse.IsSuccessStatusCode && photoResponse.Content.Headers.ContentType?.MediaType == "image/png" && (await photoResponse.Content.ReadAsByteArrayAsync()).SequenceEqual(png), "photo files served to authenticated second client");
    clientB.DefaultRequestHeaders.Authorization = null; Check((await clientB.GetAsync($"/api/photos/{photo.Id}/content")).StatusCode == HttpStatusCode.Unauthorized, "photo content never public");
}
finally { if (!process.HasExited) process.Kill(entireProcessTree: true); await process.WaitForExitAsync(); }
Console.WriteLine($"{checks} inventory server checks passed. Test artifacts: {root}");
